# permissions for end users to edit elastalerts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elastalert-editor-role
rules:
- apiGroups:
  - es.noah.domain
  resources:
  - elastalerts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - es.noah.domain
  resources:
  - elastalerts/status
  verbs:
  - get
