# permissions for end users to view elastalerts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elastalert-viewer-role
rules:
- apiGroups:
  - es.noah.domain
  resources:
  - elastalerts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - es.noah.domain
  resources:
  - elastalerts/status
  verbs:
  - get
