
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - es.noah.domain
  resources:
  - elastalerts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - es.noah.domain
  resources:
  - elastalerts/finalizers
  verbs:
  - update
- apiGroups:
  - es.noah.domain
  resources:
  - elastalerts/status
  verbs:
  - get
  - patch
  - update
