apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elastalert-operator
rules:
- apiGroups:
  - es.noah.domain
  resources:
  - elastalerts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - es.noah.domain
  resources:
  - elastalerts/finalizers
  verbs:
  - update
- apiGroups:
  - es.noah.domain
  resources:
  - elastalerts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  - configmaps
  - events
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
